
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __TYPE_BUILTINS_H__
#define __TYPE_BUILTINS_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "gtkwidgetprofiler.h" */
GType gtk_widget_profiler_report_get_type (void) G_GNUC_CONST;
#define GTK_TYPE_WIDGET_PROFILER_REPORT (gtk_widget_profiler_report_get_type ())
G_END_DECLS

#endif /* __TYPE_BUILTINS_H__ */

/* Generated data ends here */

